# Generated by Django 4.1.5 on 2023-01-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='rating',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='rating'),
        ),
    ]
