# Generated by Django 4.1.5 on 2023-02-08 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_songs_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='app.author'),
        ),
    ]
