# Generated by Django 4.1.5 on 2023-02-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_songs_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='rating',
            field=models.CharField(blank=True, default=2.5, max_length=3, null=True, verbose_name='rating'),
        ),
    ]
