# Generated by Django 4.1.5 on 2023-02-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_songs_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='rating',
            field=models.IntegerField(blank=True, max_length=3, null=True, verbose_name='rating'),
        ),
    ]
