# Generated by Django 4.1.5 on 2023-02-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_songs_author_alter_songs_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='image',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
