# Generated by Django 4.1.5 on 2023-02-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_songs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='images/'),
        ),
    ]
