# Generated by Django 4.1.5 on 2023-02-19 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_songs_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='file',
            field=models.FileField(default=None, upload_to='songs/'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.category'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='name',
            field=models.CharField(max_length=64, verbose_name='name'),
        ),
    ]
