# Generated by Django 4.1.5 on 2023-02-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_songs_file_alter_songs_category_alter_songs_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='file',
            field=models.FileField(upload_to='songs/'),
        ),
    ]
