# Generated by Django 4.1.5 on 2023-02-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_songs_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='songs',
            name='new_author',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='new_author_name'),
        ),
    ]
