# Generated by Django 4.1.5 on 2023-02-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_delete_author_songs_new_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='username')),
            ],
        ),
        migrations.RemoveField(
            model_name='songs',
            name='new_author',
        ),
    ]
