# Generated by Django 4.1.5 on 2023-02-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_author_remove_songs_new_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='author_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='author_name'),
        ),
    ]
