# Generated by Django 4.1.5 on 2023-02-23 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_user_fav_songs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
