# Generated by Django 4.1.5 on 2023-02-23 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
