# Generated by Django 4.1.5 on 2023-02-23 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fav_songs',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
