# Generated by Django 4.1.5 on 2023-02-24 10:16
from django.db import migrations, models




class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favors',
            field=models.ManyToManyField(to='app.songs'),
        ),
    ]
