# Generated by Django 4.1.5 on 2023-02-26 08:04

import django.core.validators
from django.db import migrations, models
from django.contrib.auth.models import User


def generate_superuser(apps, schema_editor):
    # User = apps.get_model("users.User")
    User.objects.create_superuser(
        username="NewAdmin",
        email="some_email@gmail.com",
        password="Password@5hk@",
    )

    print("\nInitial superuser created\n")


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_songs_file'),
    ]

    operations = [
        migrations.RunPython(generate_superuser)
    ]
