# Generated by Django 4.1.5 on 2023-03-02 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_data_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
