# Generated by Django 4.1.5 on 2023-02-26 08:04

import django.core.validators
from django.db import migrations, models
from django.contrib.auth.models import User
from app.models import Category


def generate_categories(apps, schema_editor):
    categories = ['Грустная', 'Веселая', 'Детская', 'Рок', 'Джаз', 'Поп']
    for i in range(1, len(categories)):
        new_category = Category(title=categories[i],)
        new_category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_songs_date'),
    ]

    operations = [
        migrations.RunPython(generate_categories)
    ]
